version: "3.3"
services:
  jussi:
    restart: "no"
    container_name: jussi
    image: "golosblockchain/jussi:latest"
    ports:
      - "8080:8080"
    environment:
      JUSSI_REDIS_URL: redis://redis1:6379
    volumes:
      - ./DEV_config.json:/app/DEV_config.json
  redis1:
    restart: "no"
    container_name: redis
    image: "redis:3.2"
