version: "3"
services:

  jussi:
    image: golosblockchain/jussi:latest
    volumes:
      - ./DEV_config.json:/app/DEV_config.json
    ports:
      - "8080:8080"
    environment:
      JUSSI_REDIS_URL: redis://redis:6379

  redis:
    image: redis:3.2